### ISSUE TITLE
How to load an .obj file as terrain in Isaac Gym

### ISSUE THREAD

**Issue by cometlogic** [leggedrobotics/terrain-generator#8]
The paper successfully loads the generated environment into Isaac Gym as new terrain. How is this achieved?

**Comment by mktk1117** [comment]
You can call gym.add_triangle_mesh function to add mesh.
reference: https://github.com/isaac-sim/IsaacGymEnvs/blob/aeed298638a1f7b5421b38f5f3cc2d1079b6d9c3/isaacgymenvs/tasks/anymal_terrain.py#L208

**Comment by cometlogic** [comment]
@mktk1117 Hi! Thanks a lot for your response. The official Isaac Gym documentation states that the add_triangle_mesh function adds a ground heightfield to the simulation. I couldn't find a parameter for specifying an .obj file path.

**Comment by cometlogic** [comment]
@mktk1117 Oh, thank you very much. I understand what you mean now, and I successfully achieved it with your guidance! Thank you!

**Comment by jingdaliang** [comment]
Hello, I was wondering if you are directly calling the radar in the gym and using the generated terrain as input?

**Comment by cometlogic** [comment]
@jingdaliang Hi, I did not use the radar. By the way, how do you add radar in gym?

**Comment by jingdaliang** [comment]
I don't really understand this part, this is my next direction, we can communicate together

**Comment by mktk1117** [comment]
You can check this implementation.
https://github.com/isaac-sim/IsaacLab/blob/main/source/extensions/omni.isaac.lab/omni/isaac/lab/sensors/ray_caster/ray_caster.py

**Comment by jingdaliang** [comment]
Is it based on Isaac Gym that can't add radar to quadruped robots?

**Comment by junjiehuang12** [comment]
> @mktk1117 Oh, thank you very much. I understand what you mean now, and I successfully achieved it with your guidance! Thank you!

Hello, how did you achieve it?

**Comment by HaodongHuang-W** [comment]
@HY-warehouse  I would like to ask how to import it in Isaac Gym. Is it done in `terrain.py`? Thank you very much.
